# Name of website
title: Jiang Sheng's documentation

# Your name to show in the footer
author: Sheng Jiang

navbar-links:
Author's home: "https://jiangsheng.net"
social-network-links:
  [github:jiangsheng](https://github.com/jiangsheng/)
  twitter (archived): jiangsheng
  [bluesky:sheng-jiang.bsky.social](https://bsky.app/profile/sheng-jiang.bsky.social)
  [stackoverflow:Sheng Jiang 蒋晟](https://stackoverflow.com/users/109919/sheng-jiang-%e8%92%8b%e6%99%9f")

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Exclude these files from production site
exclude:
- docs/
include: [_static]